import { describe, expect, it } from 'vitest'
import { eclipticOfDate, degreeInSign, normaliseDegrees, positionOf, signOf } from '../ephemeris.ts'
import type { BodyId } from '../types.ts'
import reference from './fixtures/horizons-raw.json' with { type: 'json' }

/**
 * Validation against NASA/JPL Horizons.
 *
 * The expected values were generated by Horizons, an entirely independent
 * ephemeris, and committed under fixtures/. They are never regenerated from
 * SYDERA's own output — see docs/ASTROLOGY_VALIDATION.md.
 *
 * Tolerances, fixed before implementation:
 *   Sun and planets   <= 1 arcminute
 *   Moon              <= 2 arcminutes
 */
const ARCMINUTE = 1 / 60
const PLANET_TOLERANCE = 1 * ARCMINUTE
const MOON_TOLERANCE = 2 * ARCMINUTE

interface BodyRow {
  instant: string
  body: string
  longitude: number
  latitude: number
}

const rows = reference.bodyRows as BodyRow[]

function angularDifference(a: number, b: number): number {
  let delta = Math.abs(normaliseDegrees(a) - normaliseDegrees(b))
  if (delta > 180) delta = 360 - delta
  return delta
}

describe('planetary longitudes against JPL Horizons', () => {
  const deviations: Array<{ body: string; instant: string; arcminutes: number }> = []

  for (const row of rows) {
    const body = row.body.toLowerCase() as BodyId
    const tolerance = body === 'moon' ? MOON_TOLERANCE : PLANET_TOLERANCE

    it(`${row.body} at ${row.instant} is within ${(tolerance * 60).toFixed(0)}'`, () => {
      const computed = eclipticOfDate(body, Date.parse(row.instant))
      const deviation = angularDifference(computed.longitude, row.longitude)
      deviations.push({ body: row.body, instant: row.instant, arcminutes: deviation * 60 })
      expect(
        deviation,
        `${row.body} ${row.instant}: SYDERA ${computed.longitude.toFixed(6)}° vs Horizons ${row.longitude.toFixed(6)}° = ${(deviation * 60).toFixed(3)}'`,
      ).toBeLessThanOrEqual(tolerance)
    })
  }

  it('reports the observed maximum deviation per body', () => {
    const worst = new Map<string, number>()
    for (const entry of deviations) {
      worst.set(entry.body, Math.max(worst.get(entry.body) ?? 0, entry.arcminutes))
    }
    const summary = [...worst.entries()]
      .sort((a, b) => b[1] - a[1])
      .map(([body, arcmin]) => `${body}=${arcmin.toFixed(3)}'`)
      .join(' ')
    // Printed so deviations are visible rather than hidden by a passing suite.
    console.log(`    max deviation vs Horizons: ${summary}`)
    expect(worst.size).toBe(10)
  })
})

describe('ecliptic latitudes against JPL Horizons', () => {
  it('agrees within 1 arcminute for every body and instant', () => {
    for (const row of rows) {
      const body = row.body.toLowerCase() as BodyId
      const computed = eclipticOfDate(body, Date.parse(row.instant))
      const deviation = Math.abs(computed.latitude - row.latitude)
      expect(
        deviation,
        `${row.body} ${row.instant}: latitude ${computed.latitude.toFixed(6)}° vs ${row.latitude.toFixed(6)}°`,
      ).toBeLessThanOrEqual(2 * ARCMINUTE)
    }
  })
})

describe('zodiac mapping', () => {
  it('maps longitudes to the twelve signs', () => {
    expect(signOf(0)).toBe('ariete')
    expect(signOf(29.99)).toBe('ariete')
    expect(signOf(30)).toBe('toro')
    expect(signOf(180)).toBe('bilancia')
    expect(signOf(359.99)).toBe('pesci')
    expect(signOf(360)).toBe('ariete')
    expect(signOf(-1)).toBe('pesci')
  })

  it('reports the degree within the sign', () => {
    expect(degreeInSign(0)).toBeCloseTo(0, 9)
    expect(degreeInSign(45)).toBeCloseTo(15, 9)
    expect(degreeInSign(359)).toBeCloseTo(29, 9)
  })

  it('places the Sun of the 1984 fixture in Capricorn', () => {
    // Horizons: 298.364023° -> 298.364023 / 30 = sign index 9 (capricorno)
    const position = positionOf('sun', Date.parse('1984-01-19T06:30:00Z'))
    expect(position.sign).toBe('capricorno')
    expect(position.degreeInSign).toBeGreaterThan(28)
    expect(position.degreeInSign).toBeLessThan(29)
  })
})

describe('daily motion and retrograde detection', () => {
  it('gives the Sun about one degree per day, always direct', () => {
    const position = positionOf('sun', Date.parse('2000-01-01T12:00:00Z'))
    expect(position.dailyMotion).toBeGreaterThan(0.9)
    expect(position.dailyMotion).toBeLessThan(1.05)
    expect(position.retrograde).toBe(false)
  })

  it('gives the Moon about thirteen degrees per day', () => {
    const position = positionOf('moon', Date.parse('2000-01-01T12:00:00Z'))
    expect(position.dailyMotion).toBeGreaterThan(11)
    expect(position.dailyMotion).toBeLessThan(15)
  })

  it('detects a documented retrograde interval', () => {
    // Mercury was retrograde in mid-March 2018 (station 22 March 2018).
    const retrograde = positionOf('mercury', Date.parse('2018-03-28T00:00:00Z'))
    expect(retrograde.retrograde).toBe(true)
    expect(retrograde.dailyMotion).toBeLessThan(0)
  })
})

describe('determinism', () => {
  it('returns identical values for identical input', () => {
    const at = Date.parse('1984-01-19T06:30:00Z')
    expect(positionOf('mars', at)).toEqual(positionOf('mars', at))
  })
})
